<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Designer/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["Designer/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
            <th>Firstname</th>
            <th>Surname</th>
            <th>Dateofbirth</th>
            <th>Emailaddress</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $designer): ?>
            <tr>
                <td><?php echo $designer->getId() ?></td>
            <td><?php echo $designer->getFirstname() ?></td>
            <td><?php echo $designer->getSurname() ?></td>
            <td><?php echo $designer->getDateofbirth() ?></td>
            <td><?php echo $designer->getEmailaddress() ?></td>

                <td><?php echo $this->tag->linkTo(["Designer/edit/" . $designer->getId(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["Designer/delete/" . $designer->getId(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("Designer/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("Designer/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("Designer/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("Designer/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
