<style>
div.page-header {
    position: static;
	margin: 40px 40px 40px 40px;
    border: 3px solid #73AD21;
}
h1.m1 {
    position: static;
	margin: 15px 5px 5px 40px;
}
h2.m {
    position: static;
	margin: 40px 40px 40px 300px;
}
</style>
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
 
<div class="page-header" margin="100px">
    <h1 class="m1">
        Welcome in Fancy-schmancy shop, the only one in Ireland!
    </h1>
	<h2 class="m"> We will create anything for you </h2>
</div>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>

    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <img src="../../../shop/public/img/home.jpg" alt="Los Angeles" style="width:100%;">
      </div>

      <div class="item">
        <img src="../../../shop/public/img/home2.jpg" alt="Chicago" style="width:100%;">
      </div>
    
      <div class="item">
        <img src="../../../shop/public/img/home5.jpg" alt="New york" style="width:100%;">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

</body>


<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "user/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

  <form class="modal-content" action="/shop/user/login">
    <div class="container">
		<div class="form-group">
			<label for="fieldUsername" class="col-sm-2 control-label">Username</label>
			<div class="col-sm-10">
				<?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
			</div>
		</div>

		<div class="form-group">
			<label for="fieldPassword" class="col-sm-2 control-label">Password</label>
			<div class="col-sm-10">
			<?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
			</div>
		</div>

		<div class="form-group">
			<label for="fieldPassword" class="col-sm-2 control-label">Confirm Password</label>
			<div class="col-sm-10">
				<?php echo $this->tag->passwordField(["confirmpassword", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
			</div>
		</div>


		<div class="form-group">
			<label for="fieldFirstname" class="col-sm-2 control-label">Firstname</label>
			<div class="col-sm-10">
				<?php echo $this->tag->textField(["firstname", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
			</div>
		</div>

		<div class="form-group">
			<label for="fieldSurname" class="col-sm-2 control-label">Surname</label>
			<div class="col-sm-10">
				<?php echo $this->tag->textField(["surname", "size" => 30, "class" => "form-control", "id" => "fieldSurname"]) ?>
			</div>
		</div>

		<div class="form-group">
			<label for="fieldEmailaddress" class="col-sm-2 control-label">EmailAddress</label>
			<div class="col-sm-10">
				<?php echo $this->tag->textField(["emailAddress", "size" => 30, "class" => "form-control", "id" => "fieldEmailaddress"]) ?>
			</div>
		</div>


		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
				
			</div>
		</div>
	</div>
	</form>
</div>



<?php echo $this->tag->endForm(); ?>

