<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Project", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit Project
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Project/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["description", "size" => 30, "class" => "form-control", "id" => "fieldDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCustomerid" class="col-sm-2 control-label">Customerid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["customerid", "type" => "number", "class" => "form-control", "id" => "fieldCustomerid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDesignerid" class="col-sm-2 control-label">Designerid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["designerid", "type" => "number", "class" => "form-control", "id" => "fieldDesignerid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFinish" class="col-sm-2 control-label">Finish</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["finish", "type" => "date", "class" => "form-control", "id" => "fieldFinish"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
