<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Project", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create Project
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Project/create",
            "autocomplete" => "off",
            "class" => "form-horizontal",
			"enctype" => "multipart/form-data"
        ]
    );
?>


<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["description", "size" => 30, "class" => "form-control", "id" => "fieldDescription"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCustomerid" class="col-sm-2 control-label">customerid</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["customerid", "type" => "number", "class" => "form-control", "id" => "fieldCustomerid"]) ?>

</div>


<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Price</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["price", "type" => "number", "class" => "form-control", "id" => "fieldPrice"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFinish" class="col-sm-2 control-label">Finish date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->dateField(["finish", "type" => "date", "class" => "form-control", "id" => "fieldFinish"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImageFile" class="col-sm-2 control-label">Upload your Image</label>
    <div class="col-sm-10">
        <?php echo $this->tag->fileField(["imageFile", "size" => 30, "class" => "form-control", "id" => "fieldImageFile"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save Project", "class" => "btn btn-default"]) ?>
    </div>
</div>


<?php echo $this->tag->endForm(); ?>
