<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Customer", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create Customer
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Customer/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldUsername" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["username", "size" => 30, "class" => "form-control", "id" => "fieldUsername"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPassword" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
        <?php echo $this->tag->passwordField(["password", "size" => 30, "class" => "form-control", "id" => "fieldPassword"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Firstname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["firstname", "size" => 30, "class" => "form-control", "id" => "fieldFirstname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSurname" class="col-sm-2 control-label">Surname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["surname", "size" => 30, "class" => "form-control", "id" => "fieldSurname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateofbirth" class="col-sm-2 control-label">Dateofbirth</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["dateofbirth", "type" => "date", "class" => "form-control", "id" => "fieldDateofbirth"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmailaddress" class="col-sm-2 control-label">Emailaddress</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["emailaddress", "size" => 30, "class" => "form-control", "id" => "fieldEmailaddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStreet" class="col-sm-2 control-label">Street</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["street", "size" => 30, "class" => "form-control", "id" => "fieldStreet"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCity" class="col-sm-2 control-label">City</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["city", "size" => 30, "class" => "form-control", "id" => "fieldCity"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPhonenumber" class="col-sm-2 control-label">Phonenumber</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["phonenumber", "size" => 30, "class" => "form-control", "id" => "fieldPhonenumber"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
